### PR TITLE
Added Prometheus IMetricResponseWriter for ascii and protobuf

### PR DESCRIPTION
**Pull request by Rurouni**
removed net452 target because it wasn't compiling with AppMetrics.Extensions.Middleware package
Also why do we need App.Metrics.Extensions.Reporting.Prometheus project?

### CODE REVIEW

**Comment by alhardy** [comment]
That's fine re the net452 target, I've removed support on middleware for now, if there are requests for support I'll revisit, not worth the effort at the moment.

`App.Metrics.Extensions.Reporting.Prometheus` would be to push metrics to prometheus, I understand you'll be configuring prometheus to pull from an API. I can revisit the push at a later date if you're not interested in that.

**Comment by Rurouni** [comment]
Pushing metrics to prometheus is quite an edge case. First of all you can't even do it directly, you have to run https://github.com/prometheus/pushgateway as standalone app and configure prometheus to scrape from it. The idea is that you will use it only for short lived jobs. But the thing is that the project is almost unmaintained.
I am pretty sure that no one will even ask for it

**Comment by alhardy** [comment]
Oh right, in that case, won't bother ;)

What's their visualization like? Or do ppl use grafana mostly?

**Comment by Rurouni** [comment]
grafana 100%

**Comment by alhardy** [comment]
OK cool, I'm adding a sanbox project to your branch, any chance you could add a grafana dashbboard demo to the repo using some metrics recorded by that project once I'm done and some setup instructions to the readme re prometheus?

**Comment by Rurouni** [comment]
I can't promise anything but I'll try to find some time

**Comment by alhardy** [comment]
Never mind, for the grafana demo I guess it makes sense to use the "generic" dasboard I've used for other reporters

**Review by alhardy — COMMENTED** [review]
@Rurouni Looks great, tested with the sanbox project I've added. Only thing I've added (other than namespace fixes) is extension methods to configure plain text vs protobuf https://github.com/alhardy/AppMetrics.Extensions.Prometheus/blob/metric_writers/sandbox/App.Metrics.Prometheus.Sandbox/Startup.cs#L74

**Review by alhardy — APPROVED** [review]

**Pull request merged**
